export const numberLore: Record<number, { title: string; archetype: string; prose: string; shadow: string }> = {
  1: { title: "The Pioneer", archetype: "The Monad", prose: "One is the first stroke of the cosmic pen, the single point from which all geometry unfolds. You are here to lead, to originate, to stand alone in the doorway of the new.", shadow: "Isolation dressed as independence." },
  2: { title: "The Peacemaker", archetype: "The Dyad", prose: "Two is the reflection in still water, the sacred conversation between self and other. You carry the gift of diplomacy, tenderness, and the art of weaving hearts together.", shadow: "Dissolving yourself to keep the peace." },
  3: { title: "The Muse", archetype: "The Triad", prose: "Three is the child born of union, laughter spilling into song. Creative expression is your native tongue, and joy is the offering you are here to make.", shadow: "Scattering your light across too many stages." },
  4: { title: "The Architect", archetype: "The Tetrad", prose: "Four is the foundation stone, the four winds, the square that holds the temple upright. You build what endures, with patience and a craftsman's integrity.", shadow: "Rigidity where there could be grace." },
  5: { title: "The Wanderer", archetype: "The Pentad", prose: "Five is the star with open arms, the five senses thrown wide to experience. Freedom is your sacrament, and change is the road on which you find God.", shadow: "Restlessness that flees depth." },
  6: { title: "The Guardian", archetype: "The Hexad", prose: "Six is the honeycomb, perfect harmony of care and form. You are the hearth-keeper, the healer, the one whose love makes a house into a home.", shadow: "Carrying burdens that were never yours." },
  7: { title: "The Mystic", archetype: "The Heptad", prose: "Seven is the seeker in the tower, the seventh day of sacred rest. You are drawn to the hidden architecture of things, to solitude, and to wisdom earned in silence.", shadow: "Retreat that hardens into loneliness." },
  8: { title: "The Sovereign", archetype: "The Ogdoad", prose: "Eight is infinity standing upright, the balance of matter and spirit. You are built for mastery, abundance, and power wielded with a just and steady hand.", shadow: "Mistaking control for security." },
  9: { title: "The Sage", archetype: "The Ennead", prose: "Nine is the completion of the circle, the elder at the end of the long road. Compassion and wisdom flow through you toward all humanity, and endings become your art.", shadow: "Martyrdom in the name of the greater good." },
  11: { title: "The Illuminator", archetype: "Master Number", prose: "Eleven stands as twin pillars at the gate of the temple. You are a channel of intuition and spiritual electricity, here to inspire with light that is not entirely your own.", shadow: "Nervous tension from carrying too much voltage." },
  22: { title: "The Master Builder", archetype: "Master Number", prose: "Twenty-two turns visions into cathedrals. You possess the rare ability to ground the loftiest dreams into forms that serve generations.", shadow: "Paralysis under the weight of potential." },
  33: { title: "The Master Teacher", archetype: "Master Number", prose: "Thirty-three is love made into a vocation, the healer of healers. Your presence uplifts, and your compassion carries the force of devotion.", shadow: "Self-sacrifice that forgets the self." },
};
